### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Prior99** [Prior99/wildstar-map#1]
root@cronosx:/opt/wildstar#
/opt/wildstar/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
Error: not opened
    at WebSocket.send (/opt/wildstar/node_modules/ws/lib/WebSocket.js:187:16)
    at Object.Connection.send (/opt/wildstar/server/websocket_server.js:42:15)
    at /opt/wildstar/server/client.js:53:23
    at /opt/wildstar/server/client.js:57:10
    at Query._callback (/opt/wildstar/server/database.js:87:6)
    at Query.Sequence.end (/opt/wildstar/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/opt/wildstar/node_modules/mysql/lib/protocol/sequences/Query.js:143:8)
    at Query.EofPacket (/opt/wildstar/node_modules/mysql/lib/protocol/sequences/Query.js:127:8)
    at Protocol._parsePacket (/opt/wildstar/node_modules/mysql/lib/protocol/Protocol.js:251:24)
    at Parser.write (/opt/wildstar/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/opt/wildstar/node_modules/mysql/lib/protocol/Protocol.js:39:

**Comment by Prior99** [comment]
Fixed with commit https://github.com/Prior99/wildstar-map/commit/156c8bd844625d8373d4e6895acd4c0d46ddaee0
